var routes = [
  {value:"ALUR", name: "Alabama Route"},
  {value:"AKUR", name: "Alaska Route"},
  {value:"ASUR", name: "American Samoa Route"},
  {value:"AZUR", name: "Arizona Route"},
  {value:"ARUR", name: "Arkansas Route"},
  {value:"CAUR", name: "California Route"},
  {value:"COUR", name: "Colorado Route"},
  {value:"CTUR", name: "Connecticut Route"},
  {value:"DEUR", name: "Delaware Route"},
  {value:"DCUR", name: "District Of Columbia Route"},
  {value:"FMUR", name: "Federated States Of Micronesia Route"},
  {value:"FLUR", name: "Florida Route"},
  {value:"GAUR", name: "Georgia Route"},
  {value:"GUUR", name: "Guam Route"},
  {value:"HIUR", name: "Hawaii Route"},
  {value:"IDUR", name: "Idaho Route"},
  {value:"ILUR", name: "Illinois Route"},
  {value:"INUR", name: "Indiana Route"},
  {value:"IAUR", name: "Iowa Route"},
  {value:"KSUR", name: "Kansas Route"},
  {value:"KYUR", name: "Kentucky Route"},
  {value:"LAUR", name: "Louisiana Route"},
  {value:"MEUR", name: "Maine Route"},
  {value:"MHUR", name: "Marshall Islands Route"},
  {value:"MDUR", name: "Maryland Route"},
  {value:"MAUR", name: "Massachusetts Route"},
  {value:"MIUR", name: "Michigan Route"},
  {value:"MNUR", name: "Minnesota Route"},
  {value:"MSUR", name: "Mississippi Route"},
  {value:"MOUR", name: "Missouri Route"},
  {value:"MTUR", name: "Montana Route"},
  {value:"NEUR", name: "Nebraska Route"},
  {value:"NVUR", name: "Nevada Route"},
  {value:"NHUR", name: "New Hampshire Route"},
  {value:"NJUR", name: "New Jersey Route"},
  {value:"NMUR", name: "New Mexico Route"},
  {value:"NYUR", name: "New York Route"},
  {value:"NCUR", name: "North Carolina Route"},
  {value:"NDUR", name: "North Dakota Route"},
  {value:"MPUR", name: "Northern Mariana Islands Route"},
  {value:"OHUR", name: "Ohio Route"},
  {value:"OKUR", name: "Oklahoma Route"},
  {value:"ORUR", name: "Oregon Route"},
  {value:"PWUR", name: "Palau Route"},
  {value:"PAUR", name: "Pennsylvania Route"},
  {value:"PRUR", name: "Puerto Rico Route"},
  {value:"RIUR", name: "Rhode Island Route"},
  {value:"SCUR", name: "South Carolina Route"},
  {value:"SDUR", name: "South Dakota Route"},
  {value:"TNUR", name: "Tennessee Route"},
  {value:"TXUR", name: "Texas Route"},
  {value:"UTUR", name: "Utah Route"},
  {value:"VTUR", name: "Vermont Route"},
  {value:"VIUR", name: "Virgin Islands Route"},
  {value:"VAUR", name: "Virginia Route"},
  {value:"WAUR", name: "Washington Route"},
  {value:"WVUR", name: "West Virginia Route"},
  {value:"WIUR", name: "Wisconsin Route"},
  {value:"WYUR", name: "Wyoming Route"}
];
